version: "3.7"
services:
  app:
    build: .
    ports:
      - "3000:3000"
  database:
    image: mongo:4.4
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=db
      - MONGO_INITDB_USERNAME=user
      - MONGO_INITDB_PASSWORD=password
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./db:/data/db
